# Heuristics for MD Reformatter Agent
default_applyTo: "**/*.py"

rules:
  - id: prompt_section
    match_heading: ["Prompt", "Task", "Request"]
    target: prompt
    prompt_mode: agent
    description_template: "Generated prompt from section: {heading_text}"

  - id: instructions_section
    match_heading: ["Coding guidelines", "Guidelines", "Instructions"]
    target: instructions
    applyTo: "**/*.py"

  - id: chatmode_section
    match_heading: ["Mode", "Chat Mode", "Persona"]
    target: chatmode

  - id: example_section
    match_heading: ["Example", "Sample"]
    target: attach_to_prompt
    attach_to_nearest: true

  - id: default_fallback
    match_heading: []
    target: candidate
    reason: "No clear mapping; create candidate for manual review"
