augmentations:
  crop_scale:
  - 0.5
  - 1.0
  jitter_params:
    brightness: 0.2
    contrast: 0.2
    hue: 0.1
    saturation: 0.2
  rotation_degrees: 15
data:
  batch_size: 1
  data_root_path: ./dataset/coralscapes/
  dataset_name: ./dataset/coralscapes/
  num_workers: 16
  patch_size: 512
  pds_train_path: ./dataset/processed/pds_patches/
  task_definitions_path: configs/task_definitions.yaml
evaluator:
  checkpoint_path: null
  output_dir: null
loss:
  params:
    dice_smooth: 1.0
    focal_gamma: 2.0
    hybrid_alpha: 0.5
    ignore_index: 0
    primary_loss_type: focal
  type: HybridLoss
metrics:
  boundary_thickness: 4
  ignore_index: 0
model:
  params:
    backbone: nvidia/mit-b2
    decoder_channel: 256
    num_classes: 40
  type: SegFormerBaseline
optimizer:
  params:
    adam_betas:
    - 0.9
    - 0.999
    lr: 6.0e-05
    power: 1.0
    warmup_ratio: 0.1
    weight_decay: 0.01
  type: AdamWPolyDecay
trainer:
  device: cuda
  epochs: 1
  gradient_accumulation_steps: 4
  inference_batch_size: 16
  inference_stride: 256
  model_selection_metric: global.BIoU
  output_dir: experiments/test_fix_validation
  use_mixed_precision: true
