import argparse
from pathlib import Path
import os
from typing import Optional

# Direct imports from the other pipeline scripts
# This assumes the script is run from the project's root directory,
# so the 'scripts' directory is on the Python path.
from create_pds_dataset import create_pds_dataset
from analyze_patch_distribution import analyze_distribution
from compare_distributions import compare_and_visualize

def create_pds_patches_and_report(
    dataset_root: Path,
    pds_output_dir: Path,
    analysis_output_dir: Path,
    patch_size: int,
    pds_radius: int,
    num_workers: int,
    task_definition_path: Optional[Path]
):
    """
    Orchestrates the sequential execution of the data pipeline by directly
    calling the imported functions from the other scripts.
    """
    print("--- Starting Coral-MTL Data Pipeline Orchestration ---")

    # --- Step 1: Create the PDS-sampled patch dataset ---
    print("\n--- Running: Step 1 - Create PDS Dataset ---")
    create_pds_dataset(
        dataset_root=str(dataset_root),
        output_dir=str(pds_output_dir),
        patch_size=patch_size,
        pds_radius=pds_radius,
        num_workers=num_workers,
        task_definition_path=str(task_definition_path) if task_definition_path else None
    )
    print("--- Finished: Step 1 ---")

    # --- Step 2: Analyze the distribution of the newly created patch dataset ---
    print("\n--- Running: Step 2 - Analyze Patch Distribution ---")
    pds_analysis_out_dir = analysis_output_dir / "pds_analysis"
    pds_analysis_out_dir.mkdir(parents=True, exist_ok=True) # Ensure output dir exists
    analyze_distribution(
        patch_dir=pds_output_dir,
        output_dir=pds_analysis_out_dir
    )
    print("--- Finished: Step 2 ---")

    # --- Step 3: Compare the new distribution against the original dataset ---
    print("\n--- Running: Step 3 - Compare Distributions ---")
    comparison_out_dir = analysis_output_dir / "comparison_results"
    comparison_out_dir.mkdir(parents=True, exist_ok=True) # Ensure output dir exists
    compare_and_visualize(
        original_dataset_root=dataset_root,
        pds_patch_dir=pds_output_dir,
        output_dir=comparison_out_dir,
        task_definition_path=task_definition_path
    )
    print("--- Finished: Step 3 ---")

    print("\n--- Coral-MTL Data Pipeline Orchestration Complete ---")
    print(f"All outputs can be found in '{pds_output_dir}' and '{analysis_output_dir}'.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Orchestrates the Coral-MTL data preparation and analysis pipeline."
    )
    parser.add_argument(
        "--dataset_root", type=str, required=True,
        help="Path to the root of the original 'coralscapes' directory (contains 'leftImg8bit' and 'gtFine')."
    )
    parser.add_argument(
        "--pds_output_dir", type=str, default="./data/processed/pds_patches",
        help="Directory where the PDS-generated patch dataset will be saved."
    )
    parser.add_argument(
        "--analysis_output_dir", type=str, default="./experiments/data_analysis",
        help="Root directory for all analysis reports and plots generated by scripts 2 and 3."
    )
    parser.add_argument(
        "--patch_size", type=int, default=512,
        help="Width and height of the square patches to extract."
    )
    parser.add_argument(
        "--pds_radius", type=int, default=300,
        help="Minimum distance between the centers of any two patches for Poisson Disk Sampling."
    )
    parser.add_argument(
        "--num_workers", type=int, default=os.cpu_count(),
        help="Number of CPU cores to use for parallel processing during PDS dataset creation."
    )
    parser.add_argument(
        "--task_definition_path", type=str, default=None,
        help="Optional: Path to a YAML file defining the class remapping for flattening labels."
    )
    
    args = parser.parse_args()

    create_pds_patches_and_report(
        dataset_root=Path(args.dataset_root),
        pds_output_dir=Path(args.pds_output_dir),
        analysis_output_dir=Path(args.analysis_output_dir),
        patch_size=args.patch_size,
        pds_radius=args.pds_radius,
        num_workers=args.num_workers,
        task_definition_path=Path(args.task_definition_path) if args.task_definition_path else None
    )